### ISSUE TITLE
Using recipient validation

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto_emails#89]
@ghousemohamed _a Let me know your thoughts on this

https://www.loom.com/share/0418c6fdc2244cf194ba28f47485d883
and
https://www.loom.com/share/016cf9b3729d4eaa9d4a19385e125209

**Comment by ghousemohamed** [comment]
@neerajdotname

Since in all neeto applications, we are using the `@neeto.com` domain, there is a problem with
where to place this recipient email validation. We could do it at just the neetoAuth login/signup
level, and leave it there. But since it's possible some applications may be sending out emails to
recipients who are outside the neetoAuth's email validation lifecycle, we might be missing out on
placing validations in points of our systems where there could potentially be a collection of invalid
recipients, which in return could badly affect our sending reputation. To account for this, if we are 
deciding to place where ever appropriate an intermediary gem that will validate emails using the 
SparkPost APIs and add them to SparkPost suppression lists, we need to be able to keep track of
the list of emails we have already validated in a separate table so that we are not revalidating them.
Now since in production, the number of applications could go up to 20, we should be maintaining
20 different tables, all of which could be in different states. Some of them could have already validated
emails, and some not. This does not seem practical. Since we are not sending emails to only the `User`
model, in some cases we might be sending to `Contact` or some other equivalent model. This again
adds to the complexity.

Considering all this I think, we can create a gem - `ito`, which will work in this way:

Let's say we have an abstract model, which could be a `User`, a `Contact`, or any other model 
which has any field which has an email:

```ruby
class AbstractModelContainingEmailField
   include Ito::Validations # This will include the callbacks whenever emails are created or updated
   ito_field :email  # This will specify the field which will be used to verify with sparkpost. Suppose email is stored in :contact field, then we would specify ito_field :contact
   ito_model "Recipient" # This will specify the model in which after an email has been validated, a record is created.
end
```

Alternatively, in the initializer, we could specify a list of models for which we want to apply the same,
as above:

```ruby
# initializers/ito_models.rb
Ito.configure do |config|
  config.models = [
    { klass: User, field: :email, store_at: Recipient },
    { klass: Contact, field: :contact_email, store_at: Recipient },
    { klass: AbstractModel, field: :abstract_field, store_at: AbstractRecipient }
  ]
  config.provider = :sparkpost
  config.api_key = ENV["SPARKPOST_API_KEY"]
end
```

Now this will do all the configuration for us. To solve the problem of multiple tables in multiple apps,
I think we need to consider using [multiple DBs with active record](https://guides.rubyonrails.org/active_record_multiple_databases.html). The second DB will be solely for reci-
-pient validated emails. We can create this DB in the neeto-auth-production instance of Heroku, and use
the HOST, DB_NAME envs, etc in each respective application so that the `Recipient` table uses the 
same source of truth.

What do you think?

**Comment by neerajdotname** [comment]
@ghousemohamed https://www.loom.com/share/2c24cea05dcd40e687d6b9c42f076f3e

**Comment by ghousemohamed** [comment]
Notes:

1. Having the email validation at the model level we will have to deal with latency issues.
    Because the email validation happens based on DNS lookup of MX records, SMTP con-
    -nection verification, etc, which is not a foolproof way of verifying emails. So ideally, the
    email validation should happen right before sending out the emails at the `Mailer`
    level.
2. The email validation will be a separate service on its own. Which will basically take the
     email as the param and use the SparkPost APIs to handle the verifications and store it
     in a dedicated DB for that service. All apps will be using this service.
3. To get all the apps to use this service, I believe, the easiest way to get to do this, would
     be to create a gem that uses this service internally. And initialize this gem as an interceptor
     in `neeto_commons`. So after `neeto_commons` is updated in all apps, apps should be
     having the gem as a registered interceptor, and we will verify emails from there onwards.

cc: @neerajdotname

**Comment by ghousemohamed** [comment]
Update:

Sparkpost's recipient email validation is not up to the mark of our expectations. So we should
be looking into other alternatives, namely:

1. ZeroBounce
2. [GetEmail.io](http://getemail.io/)
3. HuBuCo
4. Proofy
5. Bouncer
6. EmailVerifier
7. Clearout
8. Email Checker
9. NeverBounce

**Comment by ghousemohamed** [comment]
@neerajdotname

ZeroBounce works as expected for our use case. Can you create an account at ZeroBounce?

<img width="1390" alt="Screenshot 2022-04-04 at 1 17 58 PM" src="https://user-images.githubusercontent.com/56545288/161497914-5f590bc9-68e4-42b7-af01-d3dd39c0e661.png">

**Comment by ghousemohamed** [comment]
ZeroBounce API Credentials: https://github.com/bigbinary/neeto-engineering/wiki/Credentials#zerobounce

**Comment by ghousemohamed** [comment]
@neerajdotname

- ZeroBounce email validation has been added in this commit in mail_interceptor https://github.com/bigbinary/mail_interceptor/commit/e8f2ebefa86a7596398d97ef717a019d923c93b4
- ZeroBouce API key has been added to all apps in production
- After this [PR](https://github.com/bigbinary/neeto_commons/pull/219) in neeto_commons is merged and all apps update neeto_commons, ZeroBounce validation will be live.
