### ISSUE TITLE
Is bcc still working? 

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto_emails#91]
I'm not seeing any emails in `neeto.bcc@bigbinary.com`. Please check. 

@philson-philip _a

**Comment by neerajdotname** [comment]
@philson-philip Can you look into this on a higher priority?

**Comment by philson-philip** [comment]
@neerajdotname I am working on it.

**Comment by philson-philip** [comment]
@neerajdotname This should be fixed now. This issue occurred due to `mail_interceptor` gem fixes PR https://github.com/bigbinary/mail_interceptor/pull/34. @ghousemohamed updated the `mail_interceptor` gem in neetoAuth and it is deployed now. This will be updated in other apps due to neeto-compliance and should resolve the issue.
